# Generated by Django 4.0.4 on 2023-06-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y1', models.FloatField()),
                ('y2', models.FloatField()),
                ('z1', models.FloatField()),
                ('z2', models.FloatField()),
                ('modelid', models.IntegerField()),
                ('rotate', models.FloatField()),
                ('rate', models.FloatField()),
                ('ratecount', models.IntegerField()),
            ],
            options={
                'db_table': 'rates',
            },
        ),
    ]
